keep track of what tests have failed

diff --git a/scripts/run-maestro-tests b/scripts/run-maestro-tests
--- a/scripts/run-maestro-tests
+++ b/scripts/run-maestro-tests
@@ -23,7 +23,19 @@ else
 fi
 
 allTestFiles=$(ls ./e2e-tests/*.yml)
+failedTests=()
 for file in $allTestFiles
 do
-   maestro test "$file" -e APP_ID="$APPID"
+  if ! maestro test "$file" -e APP_ID="$APPID";
+  then
+    failedTests+=("$file")
+  fi
 done
+
+if [ ${#failedTests[@]} -eq 0 ]; then
+    exit 0
+else
+    echo "These tests failed:"
+    printf '%s\n' "${failedTests[@]}"
+    exit 1
+fi
