retry single test failures, add longer timeouts for payment sheet

diff --git a/scripts/run-maestro-tests b/scripts/run-maestro-tests
--- a/scripts/run-maestro-tests
+++ b/scripts/run-maestro-tests
@@ -33,7 +33,11 @@ for file in $allTestFiles
 do
   if ! maestro test "$file" -e APP_ID="$APPID";
   then
-    failedTests+=("$file")
+    echo "Test ${file} failed. Retrying..."
+    if ! maestro test "$file" -e APP_ID="$APPID";
+    then
+      failedTests+=("$file")
+    fi
   fi
 done
 
