Re-enable Android tests

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -7,98 +7,98 @@ on:
     branches: ['**']
 
 jobs:
-  # test-android:
-  #   name: e2e-android-test
-  #   runs-on: ubuntu-22.04
-  #   env:
-  #     MAESTRO_CLI_ANALYSIS_NOTIFICATION_DISABLED: true
-  #   steps:
-  #     - name: Delete unnecessary tools 🔧
-  #       uses: jlumbroso/free-disk-space@v1.3.1
-  #       with:
-  #         android: false # Don't remove Android tools
-  #         tool-cache: true # Remove image tool cache - rm -rf "$AGENT_TOOLSDIRECTORY"
-  #         dotnet: true # rm -rf /usr/share/dotnet
-  #         haskell: true # rm -rf /opt/ghc...
-  #         swap-storage: true # rm -f /mnt/swapfile (4GiB)
-  #         docker-images: false # Takes 16s, enable if needed in the future
-  #         large-packages: false # includes google-cloud-sdk and it's slow
+  test-android:
+    name: e2e-android-test
+    runs-on: ubuntu-22.04
+    env:
+      MAESTRO_CLI_ANALYSIS_NOTIFICATION_DISABLED: true
+    steps:
+      - name: Delete unnecessary tools 🔧
+        uses: jlumbroso/free-disk-space@v1.3.1
+        with:
+          android: false # Don't remove Android tools
+          tool-cache: true # Remove image tool cache - rm -rf "$AGENT_TOOLSDIRECTORY"
+          dotnet: true # rm -rf /usr/share/dotnet
+          haskell: true # rm -rf /opt/ghc...
+          swap-storage: true # rm -f /mnt/swapfile (4GiB)
+          docker-images: false # Takes 16s, enable if needed in the future
+          large-packages: false # includes google-cloud-sdk and it's slow
 
-  #     - name: Enable KVM group perms
-  #       run: |
-  #         echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
-  #         sudo udevadm control --reload-rules
-  #         sudo udevadm trigger --name-match=kvm
-  #         ls /dev/kvm
+      - name: Enable KVM group perms
+        run: |
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
+          ls /dev/kvm
 
-  #     - name: checkout
-  #       uses: actions/checkout@v4
+      - name: checkout
+        uses: actions/checkout@v4
 
-  #     - name: Get yarn cache directory path
-  #       id: yarn-cache-dir-path
-  #       run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: Get yarn cache directory path
+        id: yarn-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
 
-  #     - uses: actions/cache@v4
-  #       id: yarn-cache
-  #       with:
-  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-yarn-
+      - uses: actions/cache@v4
+        id: yarn-cache
+        with:
+          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
 
-  #     - name: Setup Node.js environment
-  #       uses: actions/setup-node@v2.1.5
-  #       with:
-  #         node-version: 16
+      - name: Setup Node.js environment
+        uses: actions/setup-node@v2.1.5
+        with:
+          node-version: 16
 
-  #     - name: Install React Native CLI
-  #       run: npm install react-native-cli
+      - name: Install React Native CLI
+        run: npm install react-native-cli
 
-  #     - name: Install Dependencies
-  #       run: yarn bootstrap-no-pods
+      - name: Install Dependencies
+        run: yarn bootstrap-no-pods
 
-  #     - name: Setup Java environment
-  #       uses: actions/setup-java@v4
-  #       with:
-  #         distribution: 'zulu'
-  #         java-version: '17'
+      - name: Setup Java environment
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'zulu'
+          java-version: '17'
 
-  #     - name: Gradle cache
-  #       uses: actions/cache@v4
-  #       with:
-  #         path: |
-  #           ~/.gradle/caches
-  #           ~/.gradle/wrapper
-  #         key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
+      - name: Gradle cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
 
-  #     - name: Install Maestro CLI
-  #       run: curl -Ls "https://get.maestro.mobile.dev" | bash
+      - name: Install Maestro CLI
+        run: curl -Ls "https://get.maestro.mobile.dev" | bash
 
-  #     - name: Add Maestro to path
-  #       run: echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
+      - name: Add Maestro to path
+        run: echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
 
-  #     - name: Run Android Emulator and app
-  #       uses: reactivecircus/android-emulator-runner@v2
-  #       with:
-  #         api-level: 29
-  #         arch: x86_64
-  #         target: google_apis
-  #         force-avd-creation: false
-  #         emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-  #         disable-animations: true
-  #         script: |
-  #           # Wait for system to settle
-  #           adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
-  #           # Retry once if necessary
-  #           yarn run-example-android || (sleep 60 && yarn run-example-android)
-  #           yarn test:e2e:android
+      - name: Run Android Emulator and app
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: 29
+          arch: x86_64
+          target: google_apis
+          force-avd-creation: false
+          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          disable-animations: true
+          script: |
+            # Wait for system to settle
+            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
+            # Retry once if necessary
+            yarn run-example-android || (sleep 60 && yarn run-example-android)
+            yarn test:e2e:android
 
-  #     - name: Upload test artifacts
-  #       if: always()
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: maestro-artifacts-android
-  #         path: /Users/runner/.maestro/tests/**
+      - name: Upload test artifacts
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: maestro-artifacts-android
+          path: /Users/runner/.maestro/tests/**
 
   test-ios:
     name: e2e-ios-test
